a = input()
alpha_list = []
alpha_list.append(a.count('a'))
alpha_list.append(a.count('b'))
alpha_list.append(a.count('c'))
alpha_list.append(a.count('d'))
alpha_list.append(a.count('e'))
alpha_list.append(a.count('f'))
alpha_list.append(a.count('g'))
alpha_list.append(a.count('h'))
alpha_list.append(a.count('i'))
alpha_list.append(a.count('j'))
alpha_list.append(a.count('k'))
alpha_list.append(a.count('l'))
alpha_list.append(a.count('m'))
alpha_list.append(a.count('n'))
alpha_list.append(a.count('o'))
alpha_list.append(a.count('p'))
alpha_list.append(a.count('q'))
alpha_list.append(a.count('r'))
alpha_list.append(a.count('s'))
alpha_list.append(a.count('t'))
alpha_list.append(a.count('u'))
alpha_list.append(a.count('v'))
alpha_list.append(a.count('w'))
alpha_list.append(a.count('x'))
alpha_list.append(a.count('y'))
alpha_list.append(a.count('z'))
for i in range(26):
    print(alpha_list[i], end = ' ')